---
deployment:
  tasks:
    - export DEPLOYPATH=/home/austinse/public_html/
    - /bin/cp -R repositories/Portfoliokebpage/images $DEPLOYPATH
    - /bin/cp -R repositories/Portfoliokebpage/css $DEPLOYPATH
    - /bin/cp repositories/Portfoliokebpage/index.html $DEPLOYPATH