---
deployment:
  tasks:
    - export DEPLOYPATH=/home/example/public_html/
    - /bin/cp -R repositories/Portfoliokeypage/images $DEPLOYPATH
    - /bin/cp -R repositories/Portfoliokeypage/css $DEPLOYPATH
    - /bin/cp repositories/Portfoliokeypage/index.html $DEPLOYPATH